version: '2'

# Docker compose for running and development
services:
  all:
    build: .
    entrypoint: /app/run.sh
    entrypoint: /usr/bin/env
    command: sh
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      # mount local run.py version as well
      - $PWD/run.py:/app/run-dev.py
      - /root/hd5:/root/hd5
    env_file:
      - .env

# Needed to work in Cyfronet
networks:
  default:
    driver: bridge  
    driver_opts:
      com.docker.network.driver.mtu: 1400