version: '3.0'

services:
  oneclient:
    image: docker.onedata.org/oneclient:${source_oneprovider_version}
    # image source: https://github.com/onedata/oneclient
    privileged: true
    container_name: oneclient
    stop_signal: SIGUSR1
    entrypoint: 
      - /usr/bin/env
      - bash
      - -c
      - >
        set -e ;
        trap "{ umount /mnt/oneclient ; echo Stopping_oneclient  ; }" SIGUSR1;
        oneclient --force-proxy-io --force-fullblock-read -v 2 /mnt/oneclient ;
        echo "Oneclient ready:" ;
        ls /mnt/oneclient ;
        while [ ! -f /oneclient-can-exit ] ; do sleep 2 ; done ;
    environment:  
      ONECLIENT_PROVIDER_HOSTNAME: $source_provider
      ONECLIENT_AUTHORIZATION_TOKEN: $api_token
      ONECLIENT_NO_CHECK_CERTIFICATE: 'true'
